name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          echo -n "Hello World!!"
          pwd
      - name: Print good bye
        run: echo "Done - bye!"
